title: Site

sections:
 
  pages:
    type: pages
    

  test:
    type: fields
    fields:
      navImg:
        type: files
        label: Image
        layout: cards
        max: 1
        info: "{{ file.dimensions }}"